import json
import pytest
from click.testing import CliRunner
from lattice.cli.main import cli


@pytest.fixture()
def runner():
    return CliRunner()


def test_completion_print_bash(runner):
    result = runner.invoke(cli, ["completion", "--shell", "bash", "--print"])
    assert result.exit_code == 0
    assert len(result.output.strip()) > 0


def test_completion_print_zsh(runner):
    result = runner.invoke(cli, ["completion", "--shell", "zsh", "--print"])
    assert result.exit_code == 0
    assert len(result.output.strip()) > 0


def test_completion_print_fish(runner):
    result = runner.invoke(cli, ["completion", "--shell", "fish", "--print"])
    assert result.exit_code == 0
    assert len(result.output.strip()) > 0


def test_completion_install_bash(runner, tmp_path):
    bashrc = tmp_path / ".bashrc"
    bashrc.write_text("# existing content\n")
    result = runner.invoke(
        cli,
        ["completion", "--shell", "bash", "--install"],
        env={"HOME": str(tmp_path)},
        catch_exceptions=False,
    )
    assert result.exit_code == 0
    content = bashrc.read_text()
    assert "_LATTICE_COMPLETE=bash_source lattice" in content


def test_completion_install_idempotent(runner, tmp_path):
    bashrc = tmp_path / ".bashrc"
    bashrc.write_text("# existing\n")
    env = {"HOME": str(tmp_path)}
    runner.invoke(cli, ["completion", "--shell", "bash", "--install"], env=env)
    content_after_first = (tmp_path / ".bashrc").read_text()
    runner.invoke(cli, ["completion", "--shell", "bash", "--install"], env=env)
    content_after_second = (tmp_path / ".bashrc").read_text()
    assert content_after_first == content_after_second


def test_completion_uninstall_bash(runner, tmp_path):
    bashrc = tmp_path / ".bashrc"
    bashrc.write_text('# existing\neval "$(_LATTICE_COMPLETE=bash_source lattice)"\n')
    env = {"HOME": str(tmp_path)}
    result = runner.invoke(cli, ["completion", "--shell", "bash", "--uninstall"], env=env)
    assert result.exit_code == 0
    content = bashrc.read_text()
    assert "_LATTICE_COMPLETE=bash_source lattice" not in content
    assert (tmp_path / ".bashrc.lattice.bak").exists()


def test_completion_install_fish(runner, tmp_path):
    env = {"HOME": str(tmp_path)}
    result = runner.invoke(
        cli, ["completion", "--shell", "fish", "--install"], env=env
    )
    assert result.exit_code == 0
    fish_file = tmp_path / ".config" / "fish" / "completions" / "lattice.fish"
    assert fish_file.exists()
    content = fish_file.read_text()
    assert "# Generated by lattice completion" in content


def test_completion_fish_install_idempotent(runner, tmp_path):
    env = {"HOME": str(tmp_path)}
    runner.invoke(cli, ["completion", "--shell", "fish", "--install"], env=env)
    fish_file = tmp_path / ".config" / "fish" / "completions" / "lattice.fish"
    first = fish_file.read_text()
    result = runner.invoke(
        cli, ["completion", "--shell", "fish", "--install"], env=env
    )
    assert result.exit_code == 0
    assert fish_file.read_text() == first


def test_completion_fish_install_backs_up_existing(runner, tmp_path):
    fish_file = tmp_path / ".config" / "fish" / "completions" / "lattice.fish"
    fish_file.parent.mkdir(parents=True)
    fish_file.write_text("# hand-written user completion\n")
    env = {"HOME": str(tmp_path)}
    result = runner.invoke(
        cli, ["completion", "--shell", "fish", "--install"], env=env
    )
    assert result.exit_code == 0
    backup = tmp_path / ".config" / "fish" / "completions" / "lattice.fish.lattice.bak"
    assert backup.exists()
    assert backup.read_text() == "# hand-written user completion\n"


def test_completion_fish_uninstall(runner, tmp_path):
    env = {"HOME": str(tmp_path)}
    runner.invoke(cli, ["completion", "--shell", "fish", "--install"], env=env)
    fish_file = tmp_path / ".config" / "fish" / "completions" / "lattice.fish"
    assert fish_file.exists()
    result = runner.invoke(
        cli, ["completion", "--shell", "fish", "--uninstall"], env=env
    )
    assert result.exit_code == 0
    assert not fish_file.exists()


def test_completion_print_does_not_create_dirs(runner, tmp_path):
    env = {"HOME": str(tmp_path)}
    result = runner.invoke(cli, ["completion", "--shell", "fish", "--print"], env=env)
    assert result.exit_code == 0
    assert not (tmp_path / ".config").exists()


def test_completion_mutex(runner, tmp_path):
    result = runner.invoke(
        cli,
        ["completion", "--shell", "bash", "--print", "--install"],
        env={"HOME": str(tmp_path)},
    )
    assert result.exit_code != 0
    assert "mutually exclusive" in result.output


def test_completion_install_json(runner, tmp_path):
    bashrc = tmp_path / ".bashrc"
    bashrc.write_text("")
    result = runner.invoke(
        cli,
        ["completion", "--shell", "bash", "--install", "--json"],
        env={"HOME": str(tmp_path)},
    )
    assert result.exit_code == 0
    data = json.loads(result.output)
    assert data["ok"] is True
    assert data["data"]["action"] in ("installed", "already_installed")
