"""lattice completion — shell autocompletion setup."""

from __future__ import annotations

import json
import os
import shutil
from pathlib import Path

import click
from click.shell_completion import BashComplete, FishComplete, ZshComplete

from lattice.cli.main import cli

_SHELLS = ["bash", "zsh", "fish"]
_EVAL_LINES = {
    "bash": 'eval "$(_LATTICE_COMPLETE=bash_source lattice)"',
    "zsh": 'eval "$(_LATTICE_COMPLETE=zsh_source lattice)"',
}
_FISH_MARKER = "# Generated by lattice completion"
_COMPLETE_CLASSES = {"bash": BashComplete, "zsh": ZshComplete, "fish": FishComplete}


def _detect_shell() -> str:
    shell_path = os.environ.get("SHELL", "")
    name = Path(shell_path).name.lower()
    return name if name in _SHELLS else "bash"


def _get_script(shell: str) -> str:
    cls = _COMPLETE_CLASSES[shell]
    c = cls(cli, {}, "lattice", "_LATTICE_COMPLETE")
    return c.source()


def _get_config_file(shell: str, home: Path) -> Path:
    if shell == "bash":
        return home / ".bashrc"
    if shell == "zsh":
        return home / ".zshrc"
    fish_dir = home / ".config" / "fish" / "completions"
    fish_dir.mkdir(parents=True, exist_ok=True)
    return fish_dir / "lattice.fish"


def _is_installed(shell: str, config_file: Path) -> bool:
    if not config_file.exists():
        return False
    content = config_file.read_text()
    if shell == "fish":
        return _FISH_MARKER in content
    marker = f"_LATTICE_COMPLETE={shell}_source lattice"
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            continue
        if marker in stripped:
            return True
    return False


def _install(shell: str, config_file: Path) -> None:
    if shell == "fish":
        script = _get_script("fish")
        config_file.write_text(f"{_FISH_MARKER}\n{script}")
        return
    eval_line = _EVAL_LINES[shell]
    with config_file.open("a") as f:
        f.write(f"\n{eval_line}\n")


def _uninstall(shell: str, config_file: Path) -> None:
    backup = Path(str(config_file) + ".lattice.bak")
    shutil.copy2(config_file, backup)
    if shell == "fish":
        config_file.unlink()
        return
    marker = f"_LATTICE_COMPLETE={shell}_source lattice"
    lines = config_file.read_text().splitlines(keepends=True)
    filtered = [ln for ln in lines if marker not in ln]
    config_file.write_text("".join(filtered))


@cli.command("completion")
@click.option(
    "--shell",
    "shell_name",
    type=click.Choice(_SHELLS, case_sensitive=False),
    default=None,
    help="Target shell. Auto-detected from $SHELL if omitted.",
)
@click.option(
    "--print",
    "do_print",
    is_flag=True,
    default=False,
    help="Print activation script to stdout.",
)
@click.option(
    "--install",
    "do_install",
    is_flag=True,
    default=False,
    help="Write to shell config file.",
)
@click.option(
    "--uninstall",
    "do_uninstall",
    is_flag=True,
    default=False,
    help="Remove from shell config file.",
)
@click.option(
    "--json",
    "as_json",
    is_flag=True,
    default=False,
    help="Machine-readable output.",
)
def completion_cmd(
    shell_name: str | None,
    do_print: bool,
    do_install: bool,
    do_uninstall: bool,
    as_json: bool,
) -> None:
    """Set up shell tab-completion for lattice.

    \b
    Examples:
      lattice completion                          # print script for current shell
      lattice completion --shell zsh --print      # print zsh script
      lattice completion --shell bash --install   # install for bash
      lattice completion --install                # install for detected shell
      lattice completion --shell zsh --uninstall  # remove zsh completion
    """
    if not do_print and not do_install and not do_uninstall:
        do_print = True

    shell = shell_name or _detect_shell()
    home = Path(os.environ.get("HOME", "~")).expanduser()
    config_file = _get_config_file(shell, home)

    if do_print:
        click.echo(_get_script(shell), nl=False)
        return

    if do_install:
        if _is_installed(shell, config_file):
            action = "already_installed"
            if as_json:
                click.echo(
                    json.dumps(
                        {
                            "ok": True,
                            "data": {
                                "shell": shell,
                                "file": str(config_file),
                                "action": action,
                            },
                        }
                    )
                )
            else:
                click.echo(
                    f"Completion already configured in {config_file} — no changes made.",
                    err=True,
                )
            return
        _install(shell, config_file)
        reload_hint = f"source {config_file}" if shell != "fish" else "open a new terminal"
        if as_json:
            click.echo(
                json.dumps(
                    {
                        "ok": True,
                        "data": {
                            "shell": shell,
                            "file": str(config_file),
                            "action": "installed",
                        },
                    }
                )
            )
        else:
            click.echo(
                f"Completion installed. Reload your shell or run: {reload_hint}",
                err=True,
            )
        return

    if do_uninstall:
        if not _is_installed(shell, config_file):
            if as_json:
                click.echo(
                    json.dumps(
                        {
                            "ok": True,
                            "data": {
                                "shell": shell,
                                "file": str(config_file),
                                "action": "not_found",
                            },
                        }
                    )
                )
            else:
                click.echo(f"Completion not found in {config_file}.", err=True)
            return
        _uninstall(shell, config_file)
        if as_json:
            click.echo(
                json.dumps(
                    {
                        "ok": True,
                        "data": {
                            "shell": shell,
                            "file": str(config_file),
                            "action": "removed",
                        },
                    }
                )
            )
        else:
            click.echo(
                f"Completion removed from {config_file} (backup at {config_file}.lattice.bak)",
                err=True,
            )
